name: Cross-Platform CI Pipeline

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up dependencies
      - name: Set up dependencies on Windows
        if: runner.os == 'Windows'
        run: |
          choco install sfml --version=2.5.1 --yes
        shell: cmd

      - name: Set up dependencies on macOS
        if: runner.os == 'macOS'
        run: |
          brew install sfml
        shell: bash

      # Step 3: Configure the build
      - name: Configure Build
        run: |
          mkdir build
          cd build
          cmake -G "Unix Makefiles" ..
        shell: bash

      # Step 4: Build the project
      - name: Build Project
        run: |
          cd build
          cmake --build . --config Release
        shell: bash

      # Step 5: Run tests
      - name: Run Tests
        run: |
          cd build
          ctest --output-on-failure
        shell: bash